### ISSUE TITLE
Width jitter

### ISSUE THREAD

**Issue by thomax** [VegaPublish/vega#92] opened 2018-05-01 20:02 UTC
https://sanity-io.slack.com/files/U02ACPTK2/FANHK3D7B/wayne-state_-_sanity_-_google_chrome_5_1_2018_1_46_55_pm.mp4

**Comment by thomax** [comment] 2018-05-11 11:45
Can't reproduce anymore. Waiting for confirmation from Molly/Bonnie.

**Comment by kristofferj** [comment] 2018-06-06 08:29
Is this still an issue? I think it is connected to the closed footnote issue. Cant reproduce locally

**Comment by bjoerge** [comment] 2018-06-22 08:51
Haven't seen this issue in a while, so closing.

**Closed by bjoerge** 2018-06-22 08:51 UTC
Labels: bug/minor
